# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-26 22:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='exportable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='collection',
            name='force_validate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='collection',
            name='queryable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='collection',
            name='schema',
            field=models.TextField(blank=True, null=True),
        ),
    ]
