# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-22 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_collection_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='custom_describe',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='collection',
            name='custom_describe_json',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='custom_describe_list',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='collection',
            name='custom_describe_list_json',
            field=models.TextField(blank=True, null=True),
        ),
    ]
